/**
 * Estilos inline de la aplicación MathLite.
 * Extraído de App.jsx para mantener separación de responsabilidades.
 */

export const S = {
  app: {
    fontFamily: "'IBM Plex Sans', sans-serif",
    background: 'var(--bg)',
    color: 'var(--txt)',
    fontSize: 14,
    height: '100vh',
    display: 'flex',
    flexDirection: 'column',
    overflow: 'hidden',
  },
  // Titlebar
  titlebar: {
    background: 'var(--bg2)',
    borderBottom: '1px solid var(--border)',
    padding: '8px 20px',
    display: 'flex',
    alignItems: 'center',
    gap: 16,
    flexShrink: 0,
  },
  logo: {
    fontFamily: "'JetBrains Mono', monospace",
    fontWeight: 700,
    fontSize: 15,
    letterSpacing: '-0.02em',
    color: 'var(--txt)',
  },
  logoSpan: { color: 'var(--txt3)' },
  subtitle: {
    fontSize: 11,
    color: 'var(--txt3)',
    fontFamily: "'JetBrains Mono', monospace",
  },
  tabs: { display: 'flex', gap: 0, marginLeft: 'auto' },
  tab: (active) => ({
    fontFamily: "'JetBrains Mono', monospace",
    fontSize: 11,
    letterSpacing: '0.06em',
    padding: '6px 16px',
    cursor: 'pointer',
    color: active ? 'var(--txt)' : 'var(--txt3)',
    border: '1px solid transparent',
    borderBottom: 'none',
    borderRadius: '4px 4px 0 0',
    marginBottom: -1,
    background: active ? 'var(--bg)' : 'transparent',
    borderColor: active ? 'var(--border)' : 'transparent',
    borderBottomColor: active ? 'var(--bg)' : 'transparent',
  }),
  // Main layout
  main: { display: 'flex', flex: 1, minHeight: 0 },
  // Left panel
  left: {
    display: 'flex',
    flexDirection: 'column',
    width: '46%',
    borderRight: '1px solid var(--border)',
    minWidth: 0,
  },
  modeBar: {
    background: 'var(--bg2)',
    borderBottom: '1px solid var(--border)',
    padding: '6px 10px 0',
    display: 'flex',
    alignItems: 'center',
    gap: 10,
    flexShrink: 0,
  },
  modeTabs: { display: 'flex', gap: 0 },
  modeTab: (active) => ({
    fontFamily: "'JetBrains Mono', monospace",
    fontSize: 11,
    letterSpacing: '0.06em',
    padding: '6px 14px',
    cursor: 'pointer',
    color: active ? 'var(--txt)' : 'var(--txt3)',
    border: '1px solid transparent',
    borderBottom: 'none',
    borderRadius: '4px 4px 0 0',
    marginBottom: -1,
    background: active ? 'var(--bg)' : 'transparent',
    borderColor: active ? 'var(--border)' : 'transparent',
    borderBottomColor: active ? 'var(--bg)' : 'transparent',
  }),
  modeHint: {
    marginLeft: 'auto',
    fontFamily: "'JetBrains Mono', monospace",
    fontSize: 10,
    color: 'var(--txt3)',
    letterSpacing: '0.06em',
    paddingBottom: 6,
  },
  editorHeader: {
    background: 'var(--bg2)',
    borderBottom: '1px solid var(--border)',
    padding: '6px 14px',
    display: 'flex',
    alignItems: 'center',
    gap: 8,
    flexShrink: 0,
  },
  panelLabel: {
    fontSize: 10,
    letterSpacing: '0.09em',
    color: 'var(--txt3)',
    fontFamily: "'JetBrains Mono', monospace",
  },
  editorActions: { marginLeft: 'auto', display: 'flex', gap: 6 },
  btn: (variant) => ({
    fontSize: 11,
    fontFamily: "'JetBrains Mono', monospace",
    padding: '4px 12px',
    borderRadius: 3,
    border: `1px solid ${variant === 'primary' ? 'var(--txt)' : variant === 'danger' ? '#CCA0A0' : 'var(--border2)'}`,
    background: variant === 'primary' ? 'var(--txt)' : 'var(--bg)',
    color: variant === 'primary' ? 'var(--bg)' : variant === 'danger' ? 'var(--err)' : 'var(--txt2)',
    cursor: 'pointer',
    letterSpacing: '0.04em',
  }),
  editorWrap: { flex: 1, display: 'flex', overflow: 'hidden', minHeight: 0 },
  lineNums: {
    background: 'var(--bg2)',
    borderRight: '1px solid var(--border)',
    padding: '12px 10px 12px 12px',
    fontFamily: "'JetBrains Mono', monospace",
    fontSize: 12.5,
    lineHeight: '21px',
    color: 'var(--txt3)',
    textAlign: 'right',
    userSelect: 'none',
    minWidth: 44,
    overflow: 'hidden',
    whiteSpace: 'pre',
  },
  textarea: {
    flex: 1,
    border: 'none',
    outline: 'none',
    resize: 'none',
    padding: '12px 14px',
    fontFamily: "'JetBrains Mono', monospace",
    fontSize: 12.5,
    lineHeight: '21px',
    color: 'var(--txt)',
    background: 'var(--bg)',
    tabSize: 2,
    whiteSpace: 'pre',
  },
  // Error panel
  errPanel: {
    background: '#FFFAFA',
    borderTop: '1px solid #FFDDDD',
    padding: '8px 14px',
    display: 'flex',
    flexDirection: 'column',
    gap: 4,
    flexShrink: 0,
    maxHeight: 120,
    overflowY: 'auto',
  },
  noErrors: {
    fontFamily: "'JetBrains Mono', monospace",
    fontSize: 11,
    color: 'var(--ok)',
    padding: '6px 0',
  },
  errLine: {
    fontFamily: "'JetBrains Mono', monospace",
    fontSize: 11,
    color: 'var(--err)',
    display: 'flex',
    gap: 8,
  },
  errPhase: { color: 'var(--txt3)', flexShrink: 0 },
  // Console
  console: {
    background: 'var(--con)',
    borderTop: '1px solid #000',
    flexShrink: 0,
    display: 'flex',
    flexDirection: 'column',
    height: 200,
  },
  consoleHeader: {
    padding: '6px 16px',
    display: 'flex',
    alignItems: 'center',
    gap: 8,
    borderBottom: '1px solid #222',
    flexShrink: 0,
  },
  consoleLabel: {
    fontFamily: "'JetBrains Mono', monospace",
    fontSize: 10,
    color: '#444',
    letterSpacing: '0.1em',
  },
  conClear: {
    fontFamily: "'JetBrains Mono', monospace",
    fontSize: 10,
    color: '#444',
    cursor: 'pointer',
    marginLeft: 'auto',
    padding: '2px 8px',
    border: '1px solid #333',
    borderRadius: 2,
    background: 'transparent',
  },
  consoleOutput: {
    flex: 1,
    overflowY: 'auto',
    padding: '10px 16px',
    display: 'flex',
    flexDirection: 'column',
    gap: 3,
  },
  // Right panel
  right: { flex: 1, display: 'flex', flexDirection: 'column', minWidth: 0, overflow: 'hidden' },
  // Token scroll
  tokenScroll: { flex: 1, overflow: 'auto', padding: 14 },
  // Analysis
  analysisCols: { display: 'grid', gridTemplateColumns: '1fr 1fr 1fr', flex: 1, minHeight: 0, overflow: 'hidden' },
  aCol: { display: 'flex', flexDirection: 'column', borderRight: '1px solid var(--border)', overflow: 'hidden' },
  aColHead: {
    background: 'var(--bg2)',
    borderBottom: '1px solid var(--border)',
    padding: '6px 14px',
    fontSize: 10,
    letterSpacing: '0.09em',
    color: 'var(--txt3)',
    fontFamily: "'JetBrains Mono', monospace",
    flexShrink: 0,
  },
  aColScroll: { flex: 1, overflow: 'auto', padding: '12px 14px' },
  // AST
  astWrap: {
    flex: 1,
    overflow: 'auto',
    padding: 14,
    fontFamily: "'JetBrains Mono', monospace",
    fontSize: 12,
    lineHeight: 1.7,
  },
  // Tests
  testsWrap: { flex: 1, display: 'flex', minHeight: 0, overflow: 'hidden' },
  testsList: { width: 260, borderRight: '1px solid var(--border)', overflowY: 'auto', flexShrink: 0 },
  testItem: (active) => ({
    padding: active ? '10px 11px' : '10px 14px',
    borderBottom: '1px solid var(--border)',
    cursor: 'pointer',
    display: 'flex',
    flexDirection: 'column',
    gap: 3,
    background: active ? 'var(--bg3)' : 'transparent',
    borderLeft: active ? '3px solid var(--txt)' : '3px solid transparent',
  }),
  testName: { fontSize: 12, fontWeight: 500, color: 'var(--txt)' },
  testDetail: { flex: 1, overflow: 'auto', padding: 14, display: 'flex', flexDirection: 'column', gap: 12 },
  empty: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    flex: 1,
    color: 'var(--txt3)',
    fontFamily: "'JetBrains Mono', monospace",
    fontSize: 12,
    flexDirection: 'column',
    gap: 8,
  },
}
